# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 418560076a423969fcd76a44b667e9783e77619b5c6212b3f2aa54373c61db99bc270e3b6c62f198192b0cd426c29eb7c88a59f95702e73a2ac033245fb02d59

test:
  secret_key_base: bc1822102f28d38adf85266858577a4f5dc4d32f2241b4d179e127c58e5370cf72611ba6e8396417787baecde0cdaaf51fdab9b7532630ffb19fb2f6c192ad94

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
